### ISSUE TITLE
jQuery.browser is undefined

### ISSUE THREAD

**Issue by keul** [collective/Products.Poi#30]
We are still using `jQuery.browser` on https://github.com/collective/Products.Poi/blob/91fc86a869b92eafe23e9699cb87f2eeff354ed1/Products/Poi/browser/resources/poi.js#L4 

This trigger to a JavaScript error.
Seems is needed to maintain some old IE 6 compatibility, but I think we can move on 😄

**Comment by cdw9** [comment]
that bit of code for IE has been removed in the `3.0-development` branch

**Comment by keul** [comment]
Thanks @cdw9! So: do you know if the 3.0-dev branch something will became next official release? I don't see any activity registered on https://github.com/collective/Products.Poi/blob/3.0-development/CHANGES.rst

**Comment by cdw9** [comment]
We'll get the changelog updated before an official release. Poi 3.0 will only be compatible with Plone 5, but it uses Dexterity types and has some new features. It's close to being ready as a newly-installed product, but we still have to get the migration in place for upgrades from older versions.

**Comment by mauritsvanrees** [comment]
@keul It seems fine to remove that condition. If you have a pull request, I'd be happy to make a new 2.x release with that.

**Comment by keul** [comment]
Thanks @mauritsvanrees, I will work on both this and https://github.com/collective/collective.watcherlist/issues/8 at the same moment (need few days)

**Comment by mauritsvanrees** [comment]
Fixed.

**Comment by keul** [comment]
Thanks @mauritsvanrees (sorry for not helping, I never worked on that project again)

**Comment by mauritsvanrees** [comment]
That's okay. I needed to work on this for a client.
I have released the fix in release 2.2.10.
