### ISSUE TITLE
Migration version of Poi for migrating from 2.x to 4.x

### ISSUE THREAD

**Issue by cdw9** [collective/Products.Poi#36]
A new major version of Products.Poi is almost ready for release.  The new version uses Dexterity and  is only for Plone 5. But since Poi 2.x only works in Plone 4, we need to create another version that will serve as the migration step. The `migration` branch will become Poi 3.0, and the Plone 5 version will be Poi 4.0. See the README on the `migration` branch for more specific release steps.

Other than updating the release date in CHANGES, this branch is ready to be tagged and released.

**Comment by mauritsvanrees** [comment]
I am discussing this with Chrissy over email. Expect some releases soonish.

**Comment by mauritsvanrees** [comment]
Chrissy and her colleagues and I are proud to announce various releases of Products.Poi.

- Poi 2.x is for Plone 4. Latest version is 2.3.
- Poi 3.x is an intermediate migration step needed when going from Poi 2.x to Poi 4.x. It migrates to dexterity. Latest version is 3.0.
- Poi 4.0+ only works on Plone 5. Latest version is 4.0.
