### ISSUE TITLE
'Issue workflow' link broken in README.rst

### ISSUE THREAD

**Issue by LeeBrown** [collective/Products.Poi#46]
First of all, thanks for an awesome add on.

The subject says it all.  I'm inexperienced with Plone and trying to read up and understand workflows better so I can customise the workflow for this, but the link in README.rst, https://camo.githubusercontent.com/ba74f35c60829f3f2cf093205a64b868721b6702/687474703a2f2f7777772e7369786665657475702e636f6d2f6c6f676f732f69737375652d776f726b666c6f772e706e67
goes nowhere.
I couldn't find anything useful with search engines.

**Comment by cdw9** [comment]
Here's the image, we'll need to work on updating the README.

<img width="756" alt="issue-workflow" src="https://user-images.githubusercontent.com/447195/46231289-fc16cf80-c330-11e8-9cde-54263f61a3db.png">

**Comment by LeeBrown** [comment]
Brilliant, thank you so much Chrissy.
